language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
env:
- jwtPrivateKey=movie_jwtPrivateKey db=movie_db
cache:
  directories:
  - node_modules
install:
- npm install
script:
- nohup npm run start &
- sleep 3
- npm run test
notifications:
  email:
    recipients:
    - moogunjung@gmail.com
     n_success: always
    on_failure: always
branches:
  only:
  - master
  - test-1
