language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
env:
- db='mongodb://127.0.0.1:27017/movie_ci'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- nohup npm run start &
- sleep 3
- npm run test
notifications:
  email:
    recipients:
    - moogunjung@gmail.com
    on_success: always
    on_failure: always
